### ISSUE TITLE
Glossary?

### ISSUE THREAD

**Issue by mifeng** [hummingbot/hummingbot-site#24]
Since there's a lot of trading and technical jargon involved with Hummingbot, I would love to allow users to hover over a definition of a phrase and look up the definition. I think we would use this for common abbreviations and trading terms.

In the MkDocs for Material [docs](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/?h=glossar#adding-a-glossary), it mentions using Snippets to load an `abbreviations.md` file on each page. 

Would it be possible to create a file like that and automatically append it every page on the site? Not sure if it's feasible or if it would slow down performance drastically, so this is just an idea.

**Comment by squidfunk** [comment]
> Would it be possible to create a file like that and automatically append it every page on the site? Not sure if it's feasible or if it would slow down performance drastically, so this is just an idea.

The [Snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#auto-append-snippets) extension supports auto-appending since version 8.2 of [Python Markdown Extensions](https://facelessuser.github.io/pymdown-extensions), so we can just follow the [guide on adding a glossary](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#adding-a-glossary), define the terms with the help of the Abbreviations extension in a separate file and configure Snippets to auto-append the definitions file to every Markdown file. I can set this up if you like.

Note that the Abbreviations extension only supports plain text and no advanced formatting or media.

What's probably a little more interesting in the near future is the [instant previews](https://twitter.com/squidfunk/status/1466794654213492743) feature I'm already working on, which loads a preview of the section an internal link is pointing to when the link is hovered. This would allow for building glossaries with rich-text features. The mechanics are quite simple and similar to the way glossaries can be built with abbreviations: you define a section for each term you want to explain on a dedicated page (or multiple pages) and link to them with the instant preview feature enabled. When a user hovers over the term, a preview is immediately loaded. By clicking the link, the user will jump to the section of the glossary. What's missing is, of course, auto-linking of terms, which will be added as a separate feature after I got instant previews out the door.
